services:
  app:
    build: .
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./.env:/usr/src/app/.env
      - ./public:/app/public
      - ./uploads:/app/uploads
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/visitor-management
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - HR_EMAIL=${HR_EMAIL}
      - BASE_URL=${BASE_URL}
    depends_on:
      - mongodb
    command: node server.js
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: visitor_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
